name: 'Open Issue Action'
description: 'GitHub Action to create an issue'
author: 'Your Name'

inputs:
  token:
    description: 'GitHub token with issues write permission'
    required: true
  title:
    description: 'Issue title'
    required: true
  body:
    description: 'Issue body'
    required: false
    default: ''
  assignees:
    description: 'Issue assignees (one per line)'
    required: false
    default: ''

outputs:
  issue:
    description: 'The created issue object'

runs:
  using: 'node20'
  main: 'dist/index.js'
